CREATE TABLE IF NOT EXISTS orders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  full_name VARCHAR(255) NOT NULL,
  id_card VARCHAR(32) NOT NULL,
  phone VARCHAR(32) NOT NULL,
  district VARCHAR(128) NOT NULL,
  sector VARCHAR(128) NOT NULL,
  cell VARCHAR(128) NOT NULL,
  village VARCHAR(128) NOT NULL,
  disease VARCHAR(64) NOT NULL,
  dosage VARCHAR(32) NOT NULL,
  age INT NOT NULL,
  gender VARCHAR(16) NOT NULL,
  payment_method VARCHAR(32) NOT NULL,
  medical_certificate VARCHAR(255) NULL,
  medicine_name VARCHAR(255) NULL,
  prescription_quantity VARCHAR(64) NULL,
  doctor_instructions TEXT NULL,
  doctor_advice TEXT NULL,
  adherence_plan TEXT NULL,
  doctor_reject_reason TEXT NULL,
  canceled TINYINT(1) NOT NULL DEFAULT 0,
  admin_status ENUM('pending','under_review','approved','rejected') DEFAULT 'pending',
  admin_reject_reason TEXT NULL,
  doctor_status ENUM('pending','approved','rejected') DEFAULT 'pending',
  doctor_id INT NULL,
  provider_id INT NULL,
  provider_status ENUM('unassigned','assigned','rejected') NOT NULL DEFAULT 'unassigned',
  provider_reject_reason TEXT NULL,
  provider_confirmed TINYINT(1) NOT NULL DEFAULT 0,
  provider_confirmed_qty INT NULL,
  provider_confirmed_price DECIMAL(10,2) NULL,
  provider_stock_id INT NULL,
  provider_note TEXT NULL,
  payment_status ENUM('pending','confirmed','approved','failed') DEFAULT 'pending',
  pharmacy_status ENUM('pending','ready_pickup','ready_delivery','dispatched','delivered') DEFAULT 'pending',
  invoice_status ENUM('draft','sent','paid') NULL,
  invoice_method ENUM('online','home_delivery','pharmacy_pickup') NULL,
  invoice_total DECIMAL(10,2) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_user (user_id),
  INDEX idx_doctor (doctor_id),
  INDEX idx_provider (provider_id)
);

-- MTN MoMo payment tracking
CREATE TABLE IF NOT EXISTS momo_payments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  order_id INT NOT NULL,
  reference_id VARCHAR(64) NOT NULL UNIQUE,
  msisdn VARCHAR(32) NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  currency VARCHAR(8) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  raw_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX (order_id),
  CONSTRAINT fk_momo_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
);
